name: Magic
options:
  bundleIdPrefix: com.jordao.filipe.magic
targets:
  Magic:
    type: application
    platform: iOS
    deploymentTarget: "10.0"
    sources: [Magic]
    postCompileScripts:
      - script: swiftlint lint --path "$SRCROOT/Magic"
        name: SwiftLint
    scheme:
      testTargets:
        - MagicTests
      gatherCoverageData: true
    dependencies:
      - carthage: Alamofire

  MagicTests:
    type: bundle.unit-test
    platform: iOS
    sources: [MagicTests]
    dependencies:
      - target: Magic
      - carthage: Quick
      - carthage: Nimble
      - carthage: OHHTTPStubs
